### ISSUE TITLE
Create the "one true repo" (or clean up this one!)

### ISSUE THREAD

**Issue by ggertsen** [wangwenchuan4/Project#1]
Hey guys, this is one way we can talk about issues specific to the project itself, so I'm going to try to use this a bit more often. It should help keep track of what needs to be done.

I talked to Professor Herman today, and he thinks this should be a task for the Master (@wangwenchuan4) but, if anyone wants to spearhead it that's also fine.

What we need to do is "clean up", so to say, our project a bit. Right now we have a bunch of Eclipse projects within an Eclipse project. What's probably best is if we have just one Eclipse project, and within that, a "src" file where all our code will actually be. The main problem that we would obviously encounter is testing, since everyone would want to test their code, but I think we can figure out a way to do it.

We can keep the directory system if we like (all the folders for Robot, Belts, Inventory, etc.), we'd just have to treat them as packages.

**Comment by wangwenchuan4** [comment]
Does it mean I need to delete all the eclipse projects and create one new eclipse project?

**Comment by ggertsen** [comment]
Just removing all the .project files might work, but I'm not sure. We can probably do something similar to what the Professor did, otherwise, we can do it like that but keeping our folders. I'm don't think we need the hidden files in each subfolder though.
